# 整数规划

1.标准指派模型：0-1整数规划模型

In [5]:
# 例题6.2
import numpy as np
import cvxpy as cp
c = np.array([
    [4,8,7,15,12],
    [7,9,17,14,10],
    [6,9,12,8,7],
    [6,7,14,6,10],
    [6,9,12,10,6]
])
x = cp.Variable((5,5),integer=True)
obj = cp.Minimize(cp.sum(cp.multiply(c,x)))
con = [0<=x,x<=1,
       cp.sum(x,axis=0,keepdims=True) == 1,
       cp.sum(x,axis=1,keepdims=True) == 1 ]
prob = cp.Problem(obj,con)
prob.solve(solver='GLPK_MI')
print('最优值为：',prob.value)
print('最优解为：',x.value)

最优值为： 34.0
最优解为： [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


2.广义指派模型   
1）最大化指派问题——化为标准型；    
2）人数和任务数不等的指派问题——添加虚拟的“人”或者“任务”，使两者相等，但对应的效率为0；   
3）一个人可完成多项任务的指派问题——将该人看作多个人；  
4）某项任务一定不能由某人完成——将想要的效率值取足够小；     

用软件求解广义指派模型，直接建立0-1整数规划模型，不需要划为标准型；

In [4]:
# 例题6.1.3 装箱问题
# 1.装箱总厚度最大
'''
决策变量x_ij(i=1,2;j=1,2,...,7)表示第i辆车装第j种包装箱的件数;
L_j,w_j,a_j(j=1,2...,7)表示第j种包装箱的厚度、重量和件数;
'''

'''
约束条件：
1. 件数限制 2.长度限制 3.重量限制 4.特殊限制(题目中提到的第5,6,7种有特殊的厚的限制)
目标函数：
最大化装箱的总厚度
'''

import cvxpy as cp
import numpy as np

L = np.array([48.7,52.0,61.3,72.0,48.7,52.0,64.0])
w = np.array([2000,3000,1000,500,4000,2000,1000])
a = np.array([8,7,9,6,6,4,8])
x = cp.Variable((2,7),integer=True)

obj = cp.Maximize(cp.sum(x*L))
con  = [cp.sum(x,axis=0,keepdims=True) <= a.reshape(1,7),
        x * L <=1020,
        x * w <= 40000,
        cp.sum(x[:,4:] * L[4:]) <= 302.7,
        x >=0]
prob = cp.Problem(obj,con)
prob.solve(solver='GLPK_MI',verbose=True)
print('最有值为：',prob.value)
print('最优解为: ',x.value)

                                     CVXPY                                     
                                     v1.4.2                                    
(CVXPY) Mar 17 08:04:52 PM: Your problem has 14 variables, 5 constraints, and 0 parameters.
(CVXPY) Mar 17 08:04:52 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 17 08:04:52 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 17 08:04:52 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Mar 17 08:04:52 PM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Mar 17 08:04:52 PM: Compiling problem (target solver=GLPK_MI).
(

d:\anaconda\Lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 4 times so far.

  warnings.warn(msg, UserWarning)
d:\anaconda\Lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 5 times so far.

  warnings.warn(msg, UserWarning)
d:\anaconda\Lib\site-packages\cvxpy\expression

-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Mar 17 08:04:53 PM: Problem status: optimal
(CVXPY) Mar 17 08:04:53 PM: Optimal value: 2.039e+03
(CVXPY) Mar 17 08:04:53 PM: Compilation took 1.254e-02 seconds
(CVXPY) Mar 17 08:04:53 PM: Solver (including time spent in interface) took 8.480e-01 seconds
最有值为： 2039.4
最优解为:  [[4. 1. 5. 3. 3. 2. 0.]
 [4. 6. 4. 3. 0. 1. 0.]]


In [11]:
# 例题6.1.3 装箱问题
# 2.装箱总重量最大
'''
决策变量x_ij(i=1,2;j=1,2,...,7)表示第i辆车装第j种包装箱的件数;
L_j,w_j,a_j(j=1,2...,7)表示第j种包装箱的厚度、重量和件数;
'''

'''
约束条件：
1. 件数限制 2.长度限制 3.重量限制 4.特殊限制(题目中提到的第5,6,7种有特殊的厚的限制)
目标函数：
最大化装箱的总厚度
'''

import cvxpy as cp
import numpy as np

L = np.array([48.7,52.0,61.3,72.0,48.7,52.0,64.0])
w = np.array([2000,3000,1000,500,4000,2000,1000])
a = np.array([8,7,9,6,6,4,8])
x = cp.Variable((2,7),integer=True)

obj = cp.Maximize(cp.sum(x*w))
con  = [cp.sum(x,axis=0,keepdims=True) <= a.reshape(1,7),
        x * L <=1020,
        x * w <= 40000,
        cp.sum(x[:,4:] * L[4:]) <= 302.7,
        x >=0]
prob = cp.Problem(obj,con)
prob.solve(solver='GLPK_MI',verbose=True)
print('最有值为：',prob.value)
print('最优解为: ',x.value)

                                     CVXPY                                     
                                     v1.4.2                                    
(CVXPY) Mar 17 09:36:58 PM: Your problem has 14 variables, 5 constraints, and 0 parameters.
(CVXPY) Mar 17 09:36:58 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 17 09:36:58 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 17 09:36:58 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Mar 17 09:36:58 PM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Mar 17 09:36:58 PM: Compiling problem (target solver=GLPK_MI).
(

d:\anaconda\Lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 1 times so far.

  warnings.warn(msg, UserWarning)
d:\anaconda\Lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 2 times so far.

  warnings.warn(msg, UserWarning)
d:\anaconda\Lib\site-packages\cvxpy\expression

# 非线性规划


分类：无约束线性规划、有约束线性规划（等式约束[largrange乘法]、不等式约束[罚函数法]）     

求解方法： scipy.optimize,cvxopt,cvxpy


## 用scipy.optimze 求解

In [10]:
# 例题6.4
from scipy.optimize import minimize 
from numpy import ones

def obj(x):
    x1, x2, x3 = x 
    return (2+x1)/(1+x2)-3*x1+4*x3
LB = [0.1]*3; UB = [0.9]*3
bound = tuple(zip(LB,UB))  # ((0.1, 0.9), (0.1, 0.9), (0.1, 0.9))
res = minimize(obj,ones(3),bounds=bound)  # minimize函数是调用执行的主要函数，它接受目标函数obj，初始值ones(3)，以及bounds参数. 
                                          # 这个初始猜测对优化过程的速度和结果可能有影响。一个好的初始猜测可以帮助优化算法更快地收敛到最优解。
print('最优值：',res.fun) 
print('状态：',res.success)
print('最优解：',res.x)

最优值： -0.7736842105263159
状态： True
最优解： [0.9 0.9 0.1]


## 用cvxopt.solvers 求解

## 用cvxpy求解

In [45]:
import cvxpy as cp
import numpy as np

c1 = np.array([1,1,3,4,2])
c2 = np.array([8,2,3,1,2])
c2 = -1 * c2
A = np.array([[1,1,1,1,1], [1,2,2,1,6], [2,1,6,0,0], [0,0,1,1,5]])
b = np.array([400,800,200,200])
x = cp.Variable(5, integer=True)

obj = cp.Minimize(c1*x**2 + c2*x)
con = [0 <= x, x <= 99, A@x <= b]
prob = cp.Problem(obj, con)

# 尝试使用ECOS_BB求解器
prob.solve(solver=cp.ECOS_BB)
print('最优解：', x.value)
print('最优值: ', prob.value)


最优解： [4.00000052e+00 9.99995441e-01 4.78922535e-12 4.02352057e-12
 1.00000000e+00]
最优值:  -16.999999999538367


d:\anaconda\Lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 29 times so far.

  warnings.warn(msg, UserWarning)
d:\anaconda\Lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 30 times so far.

  warnings.warn(msg, UserWarning)


In [12]:
# 6.2.3飞行管理问题
'''
目标函数： 以所有飞机的调整量的绝对值之和最小
'''

'''
a 为飞机飞行速度, a = 800 km/h;
(x_i^0,y_i^0) 为第i架飞机的初始位置,i=1,...,6;i=6为新进入的飞机;
(x_i(t),y_i(t))为第i架飞机在t时刻的位置;
θ_i^0为第i架飞机原飞行方向角,即飞行方向与x轴的夹角,0<= θ_i^0 < 2Π;
Δθ_i为第i架飞机的方向调整量: -Π/6 <= Δθ_i <= Π/6;
θ_i = θ_i^0 + Δθ_i 第i架飞机调整后的飞行方向角;
'''
# 求得a_ij^0 和 β_ij^0 的值
import numpy as np 
import pandas as pd 
x0 = np.array([150,85,150,145,130,0])
y0 = np.array([140,85,155,50,150,0])
q = np.array([243,236,220.5,159,230,52])
d = np.zeros((6,6))
a0 = np.zeros((6,6))
b0 = np.zeros((6,6))
xy0 = np.c_[x0,y0]
 
for i in range(6):
    for j in range(6): 
        d[i,j] = np.linalg.norm(xy0[i] - xy0[j])
d[np.where(d==0)] = np.inf
a0  =np.arcsin(8./d) * 180 / np.pi
xy1 = x0 + 1j* y0
xy2 = np.exp(1j * q * np.pi / 180)

for m in range(6):
    for n in range(6):
        if n != m:
            b0[m,n] = np.angle((xy2[n]-xy2[m]) / (xy1[m]-xy1[n]))
b0 = b0 * 180 / np.pi
f = pd.ExcelWriter('pan6_1.xlsx') # 创建文件对象
pd.DataFrame(a0).to_excel(f,"sheet1",index=None) # 把a0写入表单1
pd.DataFrame(b0).to_excel(f,"sheet2",index=None) # 把b0写入表单2
f.close()

In [24]:
import numpy as np 
import pandas as pd 
from scipy.optimize import minimize
a0 = pd.read_excel('pan6_1.xlsx') # 读取第一个表单
b0 = pd.read_excel('pan6_1.xlsx',1) # 读取第二个表单
a0 = a0.values; b0 = b0.values

obj = lambda x: np.sum(np.abs(x))
bound = [(-30,30) for i in range(6)]
x0 = np.ones(6)
cons = []
for i in range(5):
    for j in range(i+1,6):
        # 可能会有闭包延迟问题？？?
        cons.append({'type':'ineq','fun':lambda x: np.abs(b0[i,j] + (x[i]+x[j])/2) - a0[i,j]})
res = minimize(obj,x0,constraints=cons,bounds=bound)
print(res) 


 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.7909172985328354
       x: [ 2.533e-07  2.533e-07  2.533e-07  2.533e-07  3.955e-01
            3.955e-01]
     nit: 6
     jac: [-1.000e+00 -1.000e+00 -1.000e+00 -1.000e+00  1.000e+00
            1.000e+00]
    nfev: 54
    njev: 6


In [31]:
# 习题6.1
'''
https://blog.csdn.net/m0_66354975/article/details/126144211 答案网址
目标函数：投资收益最大
约束条件：
        1.共600百万投资资金
        2.项目1,2,3有且仅有一项被选
        3.项目3和项目4只能被选一项
        4.项目5被选的前提是项目1被选 
'''
import numpy as np
import cvxpy as cp
c = np.array([150,210,60,80,180])
b = np.array([210,300,100,130,260])
x = cp.Variable(5,integer=True)
obj = cp.Maximize(c @ x)
cons = [b @ x <=600,
        x[0] + x[1] + x[2] == 1,
        x[2] + x[3] <= 1,
        x[4] <= x[0],
        x >=0, x <= 1 ]
prob = cp.Problem(obj,cons)
prob.solve()
print('最优值：',prob.value)
print('最优解：',x.value)

最优值： 410.0
最优解： [1. 0. 0. 1. 1.]


In [48]:
# 习题6.2
import numpy as np
import cvxpy as cp

x = cp.Variable(6,integer=True)
c = np.array([3,5,2,4,2,3])
A = np.array([8,13,6,9,5,7])
obj = cp.Maximize(c @ x)
cons = [cp.sum(cp.multiply(A,x)) <= 24,
        x <= 1,
        x >= 0]
prob = cp.Problem(obj,cons)
prob.solve()
print('最优值：',prob.value)
print('最优解：',x.value)

最优值： 10.0
最优解： [1. 0. 0. 1. 0. 1.]


In [58]:
# 后一个同学的面试在前一个同学完成所有面试后才能开始
import cvxpy as cp

# 面试所需的时间
times = [
    [14, 16, 21],  # 甲
    [19, 17, 10],  # 乙
    [10, 15, 12],  # 丙
    [9, 12, 13]    # 丁
]

n = len(times)  # 同学的数量
m = len(times[0])  # 面试阶段的数量

# 决策变量，x[i][j] 表示第 i 个同学完成第 j 阶段面试的时间
x = cp.Variable((n, m), integer=True)

# 目标是最小化最晚的面试完成时间 (此处cp.max得到的是21)
objective = cp.Minimize(cp.max(x[:, -1]))

# 约束条件
constraints = []

# 同学的面试顺序必须相同，不能插队，且需按顺序进行面试
for i in range(n):
    for j in range(1, m):
        constraints.append(x[i, j] >= x[i, j-1] + times[i][j-1])

# 后一个同学的面试在前一个同学完成所有面试后才能开始
for i in range(1, n):
    constraints.append(x[i, 0] >= x[i-1, -1] + times[i-1][-1])

# 面试开始时间不能早于8:00（假设8:00为0时刻）
constraints.append(x >= 0)

# 解决问题
problem = cp.Problem(objective, constraints)
problem.solve(solver=cp.GLPK_MI)


# 输出结果
print("最早离开时间：", problem.value, "分钟后")
for i in range(n):
    for j in range(m):
        print(f"同学 {i+1} 在阶段 {j+1} 的面试结束时间：", x[i, j].value)

最早离开时间： 155.0 分钟后
同学 1 在阶段 1 的面试结束时间： 0.0
同学 1 在阶段 2 的面试结束时间： 14.0
同学 1 在阶段 3 的面试结束时间： 30.0
同学 2 在阶段 1 的面试结束时间： 51.0
同学 2 在阶段 2 的面试结束时间： 70.0
同学 2 在阶段 3 的面试结束时间： 87.0
同学 3 在阶段 1 的面试结束时间： 97.0
同学 3 在阶段 2 的面试结束时间： 107.0
同学 3 在阶段 3 的面试结束时间： 122.0
同学 4 在阶段 1 的面试结束时间： 134.0
同学 4 在阶段 2 的面试结束时间： 143.0
同学 4 在阶段 3 的面试结束时间： 155.0


In [59]:
import cvxpy as cp

# 面试所需的时间
times = [
    [14, 16, 21],  # 甲
    [19, 17, 10],  # 乙
    [10, 15, 12],  # 丙
    [9, 12, 13]    # 丁
]

n = len(times)  # 同学的数量
m = len(times[0])  # 面试阶段的数量

# 决策变量，x[i][j] 表示第 i 个同学在第 j 阶段的面试开始时间
x = cp.Variable((n, m), integer=True)

# 构造面试结束时间的向量表达式
end_times = cp.hstack([x[i, m-1] + times[i][m-1] for i in range(n)])

# 目标是最小化最晚的面试完成时间
objective = cp.Minimize(cp.max(end_times))

# 约束条件
constraints = []

# 同学的面试顺序必须相同，不能插队，且需按顺序进行面试
for i in range(n):
    for j in range(1, m):
        constraints.append(x[i, j] >= x[i, j-1] + times[i][j-1])

# 面试开始时间不能早于8:00（假设8:00为0时刻）
constraints.append(x >= 0)

# 解决问题
problem = cp.Problem(objective, constraints)
problem.solve(solver=cp.GLPK_MI)

# 输出结果
print("最早离开时间：", problem.value, "分钟后")
for i in range(n):
    for j in range(m):
        print(f"同学 {i+1} 在阶段 {j+1} 的面试开始时间：", x[i, j].value)



最早离开时间： 51.0 分钟后
同学 1 在阶段 1 的面试开始时间： 0.0
同学 1 在阶段 2 的面试开始时间： 14.0
同学 1 在阶段 3 的面试开始时间： 30.0
同学 2 在阶段 1 的面试开始时间： 0.0
同学 2 在阶段 2 的面试开始时间： 19.0
同学 2 在阶段 3 的面试开始时间： 36.0
同学 3 在阶段 1 的面试开始时间： 0.0
同学 3 在阶段 2 的面试开始时间： 10.0
同学 3 在阶段 3 的面试开始时间： 25.0
同学 4 在阶段 1 的面试开始时间： 0.0
同学 4 在阶段 2 的面试开始时间： 9.0
同学 4 在阶段 3 的面试开始时间： 21.0


In [1]:
import cvxpy as cp

# 面试所需的时间
times = [
    [14, 16, 21],  # 甲
    [19, 17, 10],  # 乙
    [10, 15, 12],  # 丙
    [9, 12, 13]    # 丁
]

n = len(times)  # 同学的数量
m = len(times[0])  # 面试阶段的数量

# 决策变量，x[i][j] 表示第 i 个同学在第 j 阶段的面试结束时间
x = cp.Variable((n, m), integer=True)

# 目标是最小化最晚的面试结束时间
objective = cp.Minimize(cp.max(x))

# 约束条件
constraints = [x >= 0]  # 面试时间不能为负

for i in range(n):
    for j in range(m):
        # 同一同学的面试需要按顺序进行
        if j > 0:
            constraints.append(x[i, j] >= x[i, j-1] + times[i][j-1]) 
        else:
            constraints.append(x[i, j] >= times[i][j-1])  # 第一阶段面试的开始时间

# 解决问题
problem = cp.Problem(objective, constraints)
problem.solve(solver=cp.GLPK_MI)

# 输出结果
print("最早离开时间：", problem.value, "分钟后")
for i in range(n):
    for j in range(m):
        print(f"同学 {i+1} 在阶段 {j+1} 的面试结束时间：", x[i, j].value)


最早离开时间： 51.0 分钟后
同学 1 在阶段 1 的面试结束时间： 21.0
同学 1 在阶段 2 的面试结束时间： 35.0
同学 1 在阶段 3 的面试结束时间： 51.0
同学 2 在阶段 1 的面试结束时间： 10.0
同学 2 在阶段 2 的面试结束时间： 29.0
同学 2 在阶段 3 的面试结束时间： 46.0
同学 3 在阶段 1 的面试结束时间： 12.0
同学 3 在阶段 2 的面试结束时间： 22.0
同学 3 在阶段 3 的面试结束时间： 37.0
同学 4 在阶段 1 的面试结束时间： 13.0
同学 4 在阶段 2 的面试结束时间： 22.0
同学 4 在阶段 3 的面试结束时间： 34.0
