# 整数规划

1.标准指派模型：0-1整数规划模型

In [5]:
# 例题6.2
import numpy as np
import cvxpy as cp
c = np.array([
    [4,8,7,15,12],
    [7,9,17,14,10],
    [6,9,12,8,7],
    [6,7,14,6,10],
    [6,9,12,10,6]
])
x = cp.Variable((5,5),integer=True)
obj = cp.Minimize(cp.sum(cp.multiply(c,x)))
con = [0<=x,x<=1,
       cp.sum(x,axis=0,keepdims=True) == 1,
       cp.sum(x,axis=1,keepdims=True) == 1 ]
prob = cp.Problem(obj,con)
prob.solve(solver='GLPK_MI')
print('最优值为：',prob.value)
print('最优解为：',x.value)

最优值为： 34.0
最优解为： [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


2.广义指派模型   
1）最大化指派问题——化为标准型；    
2）人数和任务数不等的指派问题——添加虚拟的“人”或者“任务”，使两者相等，但对应的效率为0；   
3）一个人可完成多项任务的指派问题——将该人看作多个人；  
4）某项任务一定不能由某人完成——将想要的效率值取足够小；     

用软件求解广义指派模型，直接建立0-1整数规划模型，不需要划为标准型；

In [ ]:
# 例题6.1.3 装箱问题
# 1.装箱总厚度最大
